(benchmark smt
:source { H-PILoT }
:logic AUFLIA
:category { generated }
:status unknown

:extrafuns ((d11  Int))
:extrafuns ((d12  Int))
:extrafuns ((d21  Int))
:extrafuns ((d22  Int))
:extrafuns ((d_1  Int))
:extrafuns ((d_2  Int))
:extrafuns ((e_10  Int))
:extrafuns ((e_3  Int))
:extrafuns ((e_4  Int))
:extrafuns ((e_5  Int))
:extrafuns ((e_6  Int))
:extrafuns ((e_7  Int))
:extrafuns ((e_8  Int))
:extrafuns ((e_9  Int))

:assumption (not (= d22 e_6))
:assumption (= d21 e_5)
:assumption (= d22 e_8)
:assumption (= d12 e_5)
:assumption (= d_2 (+ d12 1))
:assumption (= d_1 (+ d11 1))
:assumption (implies (= 1 d_2) (= e_3 e_6))
:assumption (implies (= 1 d_1) (= e_3 e_5))
:assumption (implies (= 1 d21) (= e_3 e_4))
:assumption (implies (= d21 d_2) (= e_4 e_6))
:assumption (implies (= d21 d_1) (= e_4 e_5))
:assumption (implies (= d_1 d_2) (= e_5 e_6))
:assumption (implies (= 1 d_2) (= e_7 e_10))
:assumption (implies (= 1 d_1) (= e_7 e_9))
:assumption (implies (= 1 d21) (= e_7 e_8))
:assumption (implies (= d21 d_2) (= e_8 e_10))
:assumption (implies (= d21 d_1) (= e_8 e_9))
:assumption (implies (= d_1 d_2) (= e_9 e_10))
:assumption (implies (= (+ 1 1) 1) (= e_7 e_3))
:assumption (implies (= (+ d21 1) 1) (= e_8 e_3))
:assumption (implies (= (+ d_1 1) 1) (= e_9 e_3))
:assumption (implies (= (+ d_2 1) 1) (= e_10 e_3))
:assumption (implies (= (+ 1 1) d21) (= e_7 e_4))
:assumption (implies (= (+ d21 1) d21) (= e_8 e_4))
:assumption (implies (= (+ d_1 1) d21) (= e_9 e_4))
:assumption (implies (= (+ d_2 1) d21) (= e_10 e_4))
:assumption (implies (= (+ 1 1) d_1) (= e_7 e_5))
:assumption (implies (= (+ d21 1) d_1) (= e_8 e_5))
:assumption (implies (= (+ d_1 1) d_1) (= e_9 e_5))
:assumption (implies (= (+ d_2 1) d_1) (= e_10 e_5))
:assumption (implies (= (+ 1 1) d_2) (= e_7 e_6))
:assumption (implies (= (+ d21 1) d_2) (= e_8 e_6))
:assumption (implies (= (+ d_1 1) d_2) (= e_9 e_6))
:assumption (implies (= (+ d_2 1) d_2) (= e_10 e_6))
)
